name: pet_tracker
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  # -----------------------------------------------------
  # UI
  # -----------------------------------------------------
  cupertino_icons: ^1.0.6
  icons_plus: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.9.0
  calendar_date_picker2: ^1.1.7

  fl_chart: ^0.70.0
  flutter_slidable: ^4.0.0

  # -----------------------------------------------------
  # Backend
  # -----------------------------------------------------
  # ->Preferences
  shared_preferences: ^2.0.6
  # -> State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.2
  # -> Api
  http: ^1.3.0
  url_launcher: ^6.3.1
  # Language
  easy_localization: ^3.0.7
  # -> Qr Code Generator
  pretty_qr_code: ^3.3.0
  permission_handler: ^11.3.0
  geolocator: ^11.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/splashpage/
    - assets/images/intropage/
    - assets/images/home/
    - assets/images/home/homepage/
    - assets/images/home/activity/

    - assets/images/other/pets/
    - assets/icons/
    - assets/icons/home/homepage/
    - assets/icons/home/map/
    - assets/translations/
    - assets/agreements/en/
    - assets/agreements/tr/
    - assets/fonts/DynaPuff.ttf

  fonts:
    - family: DynaPuff
      fonts:
        - asset: assets/fonts/DynaPuff.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
